language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

service:
  - mysql

install:
  - pip install -r requirements.txt

script:
  - python manage.py test && flake8
