# Generated by Django 3.0.2 on 2020-01-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Instrument'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Profile'),
        ),
    ]
