# Generated by Django 3.0.2 on 2020-01-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_profile_id',
            new_name='profile_id',
        ),
    ]
