# Generated by Django 3.0.2 on 2020-01-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='user_profile',
        ),
    ]
