# Generated by Django 3.0.2 on 2020-01-23 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200122_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
