# Generated by Django 3.0.2 on 2020-01-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_confirmed',
        ),
    ]
