# Generated by Django 3.0.2 on 2020-01-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_clients"),
    ]

    operations = [
        migrations.DeleteModel(name="Clients",),
    ]
