# Generated by Django 3.0.2 on 2020-01-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
    ]
